# More info on config here: https://golangci-lint.run/usage/configuration/#config-file
run:
  timeout: 30s
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - bin
    - vendor
    - 3d-party
    - var
    - tmp
    - internal/3d-party
  skip-files:
    - \.pb\.go$
    - \.pb\.gw\.go$
  #skip-dirs-use-default: true
  #modules-download-mode: readonly|vendor|mod
  modules-download-mode: readonly

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  dupl:
    threshold: 100
  goconst:
    min-len:         2
    min-occurrences: 2
 
linters:
  disable-all: true
  enable:
    - revive
    #- unparam
    - govet
    - errcheck
    - deadcode
    - structcheck
    - varcheck
    - ineffassign
    - typecheck
    - dupl
    - goconst
    - gosec
    - rowserrcheck
    - sqlclosecheck
    - predeclared
    - nilerr
    - nakedret
    - misspell
    - tagliatelle
    #- wrapcheck
    #- gofmt
    # - goimports - your IDE should do this automatically as 'On save' action anyways
    - megacheck # (staticcheck + gosimple + unused in one linter)

issues:
  exclude-use-default: false
  exclude:
    # _ instead of err checks
    - G104
    # for "public interface + private struct implementation" cases only!
    - exported func * returns unexported type *, which can be annoying to use
    # can be removed in the development phase
    # - (comment on exported (method|function|type|const)|should have( a package)? comment|comment should be of the form)
    # not for the active development - can be removed in the stable phase
    - should have a package comment, unless it's in another file for this package
    - don't use an underscore in package name
    # errcheck: Almost all programs ignore errors on these functions and in most cases it's ok
    - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv|.*Rollback). is not checked
    - should check returned error before deferring
    - should have a package comment
