graceful-shutdown: 10s
logger:
  level: INFO

extapi:
  svc:
    def-daial-duration: 10s
    sgroups:
      dial-duration: 3s #override default-connect-tmo
      address: tcp://auth.dobry-kot.ru:9000
      check-sync-status: 5s #mandatory