name: release
on:
  push:
    branches:
      - '*'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+rc[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: benjlevesque/short-sha@v3.0
        id: short-sha
        with:
          length: 8

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push goose
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.goose
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sgroups.goose:${{ github.head_ref || github.ref_name }}-${{ steps.short-sha.outputs.sha }} 

      - name: Build and push sgroups
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.sgroups
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sgroups.server:${{ github.head_ref || github.ref_name }}-${{ steps.short-sha.outputs.sha }}

      - name: Build and push terraform
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.terraform
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sgroups.terraform:${{ github.head_ref || github.ref_name }}-${{ steps.short-sha.outputs.sha }}

      - name: Build and push to-nft
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.to-nft
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sgroups.to-nft:${{ github.head_ref || github.ref_name }}-${{ steps.short-sha.outputs.sha }}
